### ISSUE TITLE
multiqc locale

### ISSUE THREAD

**Issue by snogu** [NorwegianVeterinaryInstitute/Bifrost#11]
[28/361007] NOTE: Process `run_multiqc (multiqc)` terminated with an error exit status (1) -- Execution is retried (1)
[97/1deefe] Re-submitted process > run_multiqc (multiqc)
[97/1deefe] NOTE: Process `run_multiqc (multiqc)` terminated with an error exit status (1) -- Execution is retried (2)
[1a/70f936] Re-submitted process > run_multiqc (multiqc)
[1a/70f936] NOTE: Process `run_multiqc (multiqc)` terminated with an error exit status (1) -- Execution is retried (3)
[fe/bdc10c] Re-submitted process > run_multiqc (multiqc)
ERROR ~ Error executing process > 'run_multiqc (multiqc)'

Caused by:
  Process `run_multiqc (multiqc)` terminated with an error exit status (1)

Command executed:

  if [ -f /cluster/bin/jobsetup ];
  then set +u; source /cluster/bin/jobsetup; set -u; fi
  
      multiqc fastqc_output

Command exit status:
  1

Command output:
  Starting job 24163664 ("nxf_test") on c15-27 at Mon Nov 5 15:07:50 CET 2018
  
  Currently Loaded Modulefiles:
    1) fastqc/0.11.2       2) java/jdk1.8.0_112
  
  Job script resource usage:
         JobID  MaxVMSize     MaxRSS 
  ------------ ---------- ---------- 
  24163664.ba+    523516K      2215K 
  
  Job step resource usage:
         JobID    JobName  AllocCPUS  MaxVMSize     MaxRSS    Elapsed ExitCode 
  ------------ ---------- ---------- ---------- ---------- ---------- -------- 
  24163664       nxf_test          1                         00:00:04      0:0 
  
  Job 24163664 ("nxf_test") completed on c15-27 at Mon Nov 5 15:07:53 CET 2018

Command error:
  perl: warning: Setting locale failed.
  perl: warning: Please check that your locale settings:
  	LANGUAGE = (unset),
  	LC_ALL = (unset),
  	LC_CTYPE = "UTF-8",
  	LANG = "en_US.iso885915"
      are supported and installed on your system.
  perl: warning: Falling back to the standard locale ("C").
  Traceback (most recent call last):
    File "/work/projects/nn9305k/src/anaconda3/envs/bifrost/bin/multiqc", line 766, in <module>
      multiqc()
    File "/work/projects/nn9305k/src/anaconda3/envs/bifrost/lib/python3.6/site-packages/click/core.py", line 722, in __call__
      return self.main(*args, **kwargs)
    File "/work/projects/nn9305k/src/anaconda3/envs/bifrost/lib/python3.6/site-packages/click/core.py", line 676, in main
      _verify_python3_env()
    File "/work/projects/nn9305k/src/anaconda3/envs/bifrost/lib/python3.6/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
      'for mitigation steps.' + extra)
  RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.
  
  This system lists a couple of UTF-8 supporting locales that
  you can pick from.  The following suitable locales where
  discovered: aa_DJ.utf8, aa_ER.utf8, aa_ET.utf8, af_ZA.utf8, am_ET.utf8, an_ES.utf8, ar_AE.utf8, ar_BH.utf8, ar_DZ.utf8, ar_EG.utf8, ar_IN.utf8, ar_IQ.utf8, ar_JO.utf8, ar_KW.utf8, ar_LB.utf8, ar_LY.utf8, ar_MA.utf8, ar_OM.utf8, ar_QA.utf8, ar_SA.utf8, ar_SD.utf8, ar_SY.utf8, ar_TN.utf8, ar_YE.utf8, as_IN.utf8, ast_ES.utf8, az_AZ.utf8, be_BY.utf8, ber_DZ.utf8, ber_MA.utf8, bg_BG.utf8, bn_BD.utf8, bn_IN.utf8, bo_CN.utf8, bo_IN.utf8, br_FR.utf8, bs_BA.utf8, byn_ER.utf8, ca_AD.utf8, ca_ES.utf8, ca_FR.utf8, ca_IT.utf8, crh_UA.utf8, cs_CZ.utf8, csb_PL.utf8, cv_RU.utf8, cy_GB.utf8, da_DK.utf8, de_AT.utf8, de_BE.utf8, de_CH.utf8, de_DE.utf8, de_LU.utf8, dv_MV.utf8, dz_BT.utf8, el_CY.utf8, el_GR.utf8, en_AG.utf8, en_AU.utf8, en_BW.utf8, en_CA.utf8, en_DK.utf8, en_GB.utf8, en_HK.utf8, en_IE.utf8, en_IN.utf8, en_NG.utf8, en_NZ.utf8, en_PH.utf8, en_SG.utf8, en_US.utf8, en_ZA.utf8, en_ZW.utf8, es_AR.utf8, es_BO.utf8, es_CL.utf8, es_CO.utf8, es_CR.utf8, es_DO.utf8, es_EC.utf8, es_ES.utf8, es_GT.utf8, es_HN.utf8, es_MX.utf8, es_NI.utf8, es_PA.utf8, es_PE.utf8, es_PR.utf8, es_PY.utf8, es_SV.utf8, es_US.utf8, es_UY.utf8, es_VE.utf8, et_EE.utf8, eu_ES.utf8, fa_IR.utf8, fi_FI.utf8, fil_PH.utf8, fo_FO.utf8, fr_BE.utf8, fr_CA.utf8, fr_CH.utf8, fr_FR.utf8, fr_LU.utf8, fur_IT.utf8, fy_DE.utf8, fy_NL.utf8, ga_IE.utf8, gd_GB.utf8, gez_ER.utf8, gez_ET.utf8, gl_ES.utf8, gu_IN.utf8, gv_GB.utf8, ha_NG.utf8, he_IL.utf8, hi_IN.utf8, hne_IN.utf8, hr_HR.utf8, hsb_DE.utf8, ht_HT.utf8, hu_HU.utf8, hy_AM.utf8, id_ID.utf8, ig_NG.utf8, ik_CA.utf8, is_IS.utf8, it_CH.utf8, it_IT.utf8, iu_CA.utf8, iw_IL.utf8, ja_JP.utf8, ka_GE.utf8, kk_KZ.utf8, kl_GL.utf8, km_KH.utf8, kn_IN.utf8, ko_KR.utf8, kok_IN.utf8, ks_IN.utf8, ku_TR.utf8, kw_GB.utf8, ky_KG.utf8, lg_UG.utf8, li_BE.utf8, li_NL.utf8, lo_LA.utf8, lt_LT.utf8, lv_LV.utf8, mai_IN.utf8, mg_MG.utf8, mi_NZ.utf8, mk_MK.utf8, ml_IN.utf8, mn_MN.utf8, mr_IN.utf8, ms_MY.utf8, mt_MT.utf8, my_MM.utf8, nb_NO.utf8, nds_DE.utf8, nds_NL.utf8, ne_NP.utf8, nl_AW.utf8, nl_BE.utf8, nl_NL.utf8, nn_NO.utf8, no_NO.utf8, nr_ZA.utf8, nso_ZA.utf8, oc_FR.utf8, om_ET.utf8, om_KE.utf8, or_IN.utf8, pa_IN.utf8, pa_PK.utf8, pap_AN.utf8, pl_PL.utf8, ps_AF.utf8, pt_BR.utf8, pt_PT.utf8, ro_RO.utf8, ru_RU.utf8, ru_UA.utf8, rw_RW.utf8, sa_IN.utf8, sc_IT.utf8, sd_IN.utf8, se_NO.utf8, shs_CA.utf8, si_LK.utf8, sid_ET.utf8, sk_SK.utf8, sl_SI.utf8, so_DJ.utf8, so_ET.utf8, so_KE.utf8, so_SO.utf8, sq_AL.utf8, sq_MK.utf8, sr_ME.utf8, sr_RS.utf8, ss_ZA.utf8, st_ZA.utf8, sv_FI.utf8, sv_SE.utf8, ta_IN.utf8, te_IN.utf8, tg_TJ.utf8, th_TH.utf8, ti_ER.utf8, ti_ET.utf8, tig_ER.utf8, tk_TM.utf8, tl_PH.utf8, tn_ZA.utf8, tr_CY.utf8, tr_TR.utf8, ts_ZA.utf8, tt_RU.utf8, ug_CN.utf8, uk_UA.utf8, ur_IN.utf8, ur_PK.utf8, ve_ZA.utf8, vi_VN.utf8, wa_BE.utf8, wal_ET.utf8, wo_SN.utf8, xh_ZA.utf8, yi_US.utf8, yo_NG.utf8, zh_CN.utf8, zh_HK.utf8, zh_SG.utf8, zh_TW.utf8, zu_ZA.utf8

Work dir:
  /cluster/home/snorregu/181105_bifrost_test/work/fe/bdc10c877932b3014b7fefe78aec76

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`

 -- Check '.nextflow.log' file for details
Oops .. something when wrong
Pipeline complete
Command line: nextflow -c asm_annot.config run -resume /work/projects/nn9305k/vi_src/Bifrost/asm_annot.nf -profile condaslurm --out_dir=output
Nextflow Version:	0.30.2
Command Line:		nextflow -c asm_annot.config run -resume /work/projects/nn9305k/vi_src/Bifrost/asm_annot.nf -profile condaslurm --out_dir=output
Duration:		    3m 41s
Output Directory:	output
WARN: Killing pending tasks (5)

**Comment by karinlag** [comment]
The situation turned out that this person used a Mac to log in. The iTerm that was used was setting locale on login. The solution was to go to Profiles - Advanced and turn off "Set locale environment variables on startup".
