### ISSUE TITLE
optional input corrected reads from spades?

### ISSUE THREAD

**Issue by evezeyl** [NorwegianVeterinaryInstitute/Bifrost#30]
would be nice to have optional output of error corrected reads from spades. 
In case we need them afterwards for testing parameters and remapping...

**Comment by karinlag** [comment]
May I ask why you closed this?

**Comment by evezeyl** [comment]
because made a double and the other one is better explained

**Comment by karinlag** [comment]
Will not be doing this. Files can be collected from work if needed.
