### ISSUE TITLE
Switch from SPAdes and pilon to Unicycler?

### ISSUE THREAD

**Issue by hkaspersen** [NorwegianVeterinaryInstitute/Bifrost#47]
Switching to Unicycler allows us to remove the pilon step as it is already included in the Unicycler step. 
Thoughts?

**Comment by karinlag** [comment]
We need to discuss the further life of this pipeline. Not sure where it will go considering that we are firing up IRIDA this spring.

**Comment by karinlag** [comment]
I will stick to spades for this pipeline, you have a good thing going with unicycler for yours.
